### ISSUE TITLE
Bug when using k8s namespaces other than default

### ISSUE THREAD

**Issue by ThorstenHans** [Azure/kubernetes-keyvault-flexvol#48] opened 2018-11-22 20:25 UTC
I recognized a bug when using namespaces for deployments with `keyvault-flexvol` 

I've a dedicated namespace `development` 

After deploying the`AzureIdentity`, `AzureIdentityBinding` and a `Pod` to the `development` namespace. KeyVault driver isn't able to mount the key vault flex volume. 

As a workaround the isse can be fixed by deploying both `AzureIdentity` and `AzureIdentityBinding` to the `default` namespace. 

Once that's done, the Pod from namespace `development` can grab data from Keyvault.

I think this is a critical bug which prevents me - and I can imagine others may agree on that one - from using keyvault-flexvol for real deployments

**Comment by serbrech** [comment] 2018-11-27 16:34
I believe that this behavior is caused by https://github.com/Azure/aad-pod-identity/issues/115

**Comment by ThorstenHans** [comment] 2018-11-28 18:08
Great, @serbrech thanks for linking that one

**Comment by ritazh** [comment] 2019-01-07 23:05
Closing this issue in favor of pod identity's issue.

**Closed by ritazh** 2019-01-07 23:05 UTC
