### ISSUE TITLE
Can we mount the whole keyvault instead of specific secrets

### ISSUE THREAD

**Issue by vtiwari227** [Azure/kubernetes-keyvault-flexvol#88] opened 2019-03-12 16:14 UTC
Hi, we have a use case where we want to access the long list of secrets, I was wondering if it's possible to mount the whole keyvault or do you support regex in secret name so I  can mount a list of secrets in one call instead of providing the individual secret name in the template

**Comment by ritazh** [comment] 2019-03-15 05:49
I think this is a duplicate of #73, which is an enhancement if there are enough people asking for this. Contribution welcome! Going to close this issue for now. But feel free to reopen or chime in on the other issue.

**Closed by ritazh** 2019-03-15 05:49 UTC
