### ISSUE TITLE
Tag v0.0.13 is using v0.0.12 image in deployment yaml

### ISSUE THREAD

**Issue by landintrees** [Azure/kubernetes-keyvault-flexvol#129] opened 2019-09-16 16:37 UTC
**Describe the bug**
It looks like the v0.0.13 tag just missed Rita's version bump on the kv-flexvol-installer.yaml which was updated one day after the tag for a previous commit, so pulling the v0.0.13 deployment actually installs the v0.0.12 image.

**Steps To Reproduce**
We noticed when pulling the deployment yaml like this..
  kubectl --context $CLUSTER apply -f https://raw.githubusercontent.com/Azure/kubernetes-keyvault-flexvol/v0.0.13/deployment/kv-flexvol-installer.yaml
... we were getting the v0.0.12 flexvol image. 

**Expected behavior**
It's probably intended to pull the v0.0.13 image with the the v0.0.13 tag (sorry if not)

**Comment by ritazh** [comment] 2019-09-16 16:44
Thanks for reporting this @landintrees! This is not a bug in that we always bump the image tag version in the deployment yaml after a release has been cut. LMK if you have additional questions.

**Comment by landintrees** [comment] 2019-09-17 11:13
Thanks Rita, happy to close this if it's intentional but just to confirm, if I grab the deployment that has been tagged with **v0.0.13**, should I be getting the following yaml?:

      containers:
      - name: flexvol-driver-installer
        image: "mcr.microsoft.com/k8s/flexvolume/keyvault-flexvolume:**v0.0.12**"

**Comment by ritazh** [comment] 2019-09-17 16:00
@landintrees That's right. We update the deployment yaml _after_ a release has been cut to ensure the image works as expected.

**Comment by landintrees** [comment] 2019-09-17 16:59
@ritazh Thanks! Sorry for the dumb questions but does that mean the v0.0.13 tag is moved at a later date to point to the commit with the v0.0.13 image in? How long is it usually until that happens? Is it best for us just to unpin the version and use master for now if we want the v0.0.13 image?

**Comment by ritazh** [comment] 2019-09-18 05:03
no worries! As you can see here https://github.com/Azure/kubernetes-keyvault-flexvol/commit/9d66bc071bcf759cc8e1cc85983f5e9a9930ba16 we update the deployment yaml right after we cut the v0.0.13 release. We usually try to update the yaml with the released tag as soon as a release is cut. But you are right, if you just download a release from github, it will still contain the old yaml without the updated tag.

**Comment by ritazh** [comment] 2019-09-24 18:02
Closing this issue. If you have further questions, feel free to reopen.

**Closed by ritazh** 2019-09-24 18:02 UTC
Labels: bug
